/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import pbo_2310010231.CRUD;
/**
 *
 * @author wijaya
 */
public class FramePenghasilan extends javax.swing.JFrame {

    CRUD crudObj;
    /**
     * Creates new form FramePenghasilan
     */
    public FramePenghasilan() {
        initComponents();
        this.setLocationRelativeTo(null);
        crudObj = new CRUD(); 
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Penghasilan");
        
        loadDataTabel();
        loadIdKaryawanComboBox(); 
    }
    
    public void loadDataTabel() {
        crudObj.loadData(jTable1, "SELECT * FROM penghasilan");
    }
    
    public void clearForm() {
        TextIdPenghasilan.setText("");
        ComboBoxIdKaryawan.setSelectedIndex(0);
        TextJumlahPenghasilan.setText("");
    }
    
    public void loadIdKaryawanComboBox() {
        try {
            ComboBoxIdKaryawan.removeAllItems();
            
            ResultSet rs = crudObj.koneksiDB.createStatement().executeQuery("SELECT id_karyawan, nama_karyawan FROM karyawan");
            
            ComboBoxIdKaryawan.addItem("Pilih ID Karyawan");
            
            while (rs.next()) {
                ComboBoxIdKaryawan.addItem(rs.getString("id_karyawan") + " - " + rs.getString("nama_karyawan"));
            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat ID Karyawan: " + e.getMessage());
        }
    }
    
    public String getSelectedIdKaryawan() {
        if (ComboBoxIdKaryawan.getSelectedIndex() == 0) {
            return null;
        }
        String selectedItem = ComboBoxIdKaryawan.getSelectedItem().toString();
        String idKaryawan = selectedItem.split(" ")[0];
        return idKaryawan;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextJumlahPenghasilan = new javax.swing.JTextField();
        TextIdPenghasilan = new javax.swing.JTextField();
        ComboBoxIdKaryawan = new javax.swing.JComboBox<>();
        TextPencarian = new javax.swing.JTextField();
        BtnSimpan = new javax.swing.JButton();
        BtnUbah = new javax.swing.JButton();
        BtnHapus = new javax.swing.JButton();
        BtnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Form Penghasilan");

        jLabel2.setText("Id Penghasilan");

        jLabel3.setText("Id Karyawan");

        jLabel4.setText("Jumlah Penghasilan");

        jLabel5.setText("Pencarian");

        TextPencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextPencarianKeyReleased(evt);
            }
        });

        TextIdPenghasilan.setEditable(false);
        TextIdPenghasilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextIdPenghasilanActionPerformed(evt);
            }
        });

        ComboBoxIdKaryawan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BtnSimpan.setText("Simpan");
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });

        BtnUbah.setText("Ubah");
        BtnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUbahActionPerformed(evt);
            }
        });

        BtnHapus.setText("Hapus");
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });

        BtnClear.setText("Clear");
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(TextJumlahPenghasilan, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnSimpan)
                                .addGap(37, 37, 37)
                                .addComponent(BtnUbah)
                                .addGap(27, 27, 27)
                                .addComponent(BtnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnClear))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(98, 98, 98)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(46, 46, 46)
                                .addComponent(TextIdPenghasilan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel3)
                                .addGap(27, 27, 27)
                                .addComponent(ComboBoxIdKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(TextPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(TextPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(TextIdPenghasilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxIdKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TextJumlahPenghasilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSimpan)
                    .addComponent(BtnUbah)
                    .addComponent(BtnHapus)
                    .addComponent(BtnClear))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextIdPenghasilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextIdPenghasilanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextIdPenghasilanActionPerformed

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {                                          
        try {
            String idKaryawan = getSelectedIdKaryawan();
            if (idKaryawan == null) {
                JOptionPane.showMessageDialog(null, "Pilih ID Karyawan terlebih dahulu");
            } else if (TextJumlahPenghasilan.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Jumlah Penghasilan tidak boleh kosong");
            } else {
                crudObj.simpanPenghasilan(
                    idKaryawan,
                    TextJumlahPenghasilan.getText()
                );
                loadDataTabel();
                clearForm();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }                                         

    private void BtnUbahActionPerformed(java.awt.event.ActionEvent evt) {                                        
        try {
            String idKaryawan = getSelectedIdKaryawan();
            if (TextIdPenghasilan.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Pilih data yang ingin diubah");
            } else if (idKaryawan == null) {
                JOptionPane.showMessageDialog(null, "Pilih ID Karyawan terlebih dahulu");
            } else {
                crudObj.ubahPenghasilan(
                    TextIdPenghasilan.getText(),
                    idKaryawan,
                    TextJumlahPenghasilan.getText()
                );
                loadDataTabel();
                clearForm();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }                                       

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {                                         
        try {
            if (TextIdPenghasilan.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus");
            } else {
                int Pilihan = JOptionPane.showConfirmDialog(null, "Yakin hapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                if(Pilihan == JOptionPane.YES_OPTION) {
                    crudObj.hapusPenghasilan(TextIdPenghasilan.getText());
                    loadDataTabel();
                    clearForm();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }                                        

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {                                         
        clearForm();
    }                                        

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        int baris = jTable1.getSelectedRow();
        
        String id_penghasilan = jTable1.getValueAt(baris, 0).toString();
        String id_karyawan = jTable1.getValueAt(baris, 1).toString();
        String jumlah = jTable1.getValueAt(baris, 2).toString();
        
        TextIdPenghasilan.setText(id_penghasilan);
        TextJumlahPenghasilan.setText(jumlah);
        
        for (int i = 0; i < ComboBoxIdKaryawan.getItemCount(); i++) {
            if (ComboBoxIdKaryawan.getItemAt(i).startsWith(id_karyawan + " - ")) {
                ComboBoxIdKaryawan.setSelectedIndex(i);
                break;
            }
        }
    }                                    

    private void TextPencarianKeyReleased(java.awt.event.KeyEvent evt) {                                          
        String c=TextPencarian.getText();
        String cari="select * from penghasilan where id_penghasilan like '%"+c+"%' "+
                    "or id_karyawan like '%"+c+"%' or jumlah_penghasilan like '%"+c+"%'";
        crudObj.loadData(jTable1, cari);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePenghasilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePenghasilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePenghasilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePenghasilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePenghasilan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnSimpan;
    private javax.swing.JButton BtnUbah;
    private javax.swing.JComboBox<String> ComboBoxIdKaryawan;
    private javax.swing.JTextField TextIdPenghasilan;
    private javax.swing.JTextField TextJumlahPenghasilan;
    private javax.swing.JTextField TextPencarian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}