/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import pbo_2310010231.CRUD;

/**
 *
 * @author wijaya
 */
public class FrameKaryawan extends javax.swing.JFrame {

    CRUD crudObj;
    /**
     * Creates new form FrameKaryawan
     */
    public FrameKaryawan() {
        initComponents();
        this.setLocationRelativeTo(null);
        crudObj = new CRUD(); 
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Karyawan");
        
        loadDataTabel();
        loadIdUserComboBox();
    }
    
    public void loadDataTabel() {
        crudObj.loadData(jTable1, "SELECT * FROM karyawan");
    }
    
    public void clearForm() {
        TextIdKaryawan.setText("");
        ComboBoxIdUser.setSelectedIndex(0);
        TextNamaKaryawan.setText("");
        TextEmail.setText("");
        TextAlamat.setText("");
        TextNoTelpon.setText("");
    }
    
    public void loadIdUserComboBox() {
        try {
            ComboBoxIdUser.removeAllItems();
            
            ResultSet rs = crudObj.koneksiDB.createStatement().executeQuery("SELECT id_user, username FROM users");

            ComboBoxIdUser.addItem("Pilih ID User");
            
            while (rs.next()) {
                ComboBoxIdUser.addItem(rs.getString("id_user") + " - " + rs.getString("username"));
            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat ID User: " + e.getMessage());
        }
    }
    
    public String getSelectedIdUser() {
        if (ComboBoxIdUser.getSelectedIndex() == 0) {
            return null;
        }

        String selectedItem = ComboBoxIdUser.getSelectedItem().toString();
        String idUser = selectedItem.split(" ")[0];
        return idUser;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnClear = new javax.swing.JButton();
        TextNamaKaryawan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TextIdKaryawan = new javax.swing.JTextField();
        ComboBoxIdUser = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        TextNoTelpon = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TextAlamat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextPencarian = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BtnSimpan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        BtnUbah = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        BtnHapus = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnClear.setText("Clear");
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        TextIdKaryawan.setEditable(false);
        TextIdKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextIdKaryawanActionPerformed(evt);
            }
        });

        ComboBoxIdUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Form Karyawan");

        jLabel2.setText("Pencarian");

        TextPencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextPencarianKeyReleased(evt);
            }
        });

        jLabel3.setText("Id Karyawan");

        TextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEmailActionPerformed(evt);
            }
        });

        jLabel4.setText("Id User");

        jLabel5.setText("Nama Karyawan");

        BtnSimpan.setText("Simpan");
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });

        jLabel6.setText("Email");

        BtnUbah.setText("Ubah");
        BtnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUbahActionPerformed(evt);
            }
        });

        jLabel7.setText("Alamat");

        BtnHapus.setText("Hapus");
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });

        jLabel8.setText("No Telpon");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(BtnSimpan))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextIdKaryawan)
                                    .addComponent(ComboBoxIdUser, 0, 115, Short.MAX_VALUE)
                                    .addComponent(TextNamaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(123, 123, 123)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextNoTelpon, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(TextAlamat)
                                    .addComponent(TextEmail)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnUbah)
                                .addGap(33, 33, 33)
                                .addComponent(BtnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnClear))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)))))
                .addGap(18, 18, 18)
                .addComponent(TextPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(TextPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(TextIdKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(ComboBoxIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(TextNamaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextNoTelpon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSimpan)
                    .addComponent(BtnUbah)
                    .addComponent(BtnHapus)
                    .addComponent(BtnClear))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextIdKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextIdKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextIdKaryawanActionPerformed

    private void TextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEmailActionPerformed

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {                                          
        try {
            String idUser = getSelectedIdUser();
            if (idUser == null) {
                JOptionPane.showMessageDialog(null, "Pilih ID User terlebih dahulu");
            } else if (TextNamaKaryawan.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Nama Karyawan tidak boleh kosong");
            } else {
                crudObj.simpanKaryawan(
                    idUser, 
                    TextNamaKaryawan.getText(), 
                    TextEmail.getText(), 
                    TextAlamat.getText(), 
                    TextNoTelpon.getText()
                );
                loadDataTabel();
                clearForm();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }                                         

    private void BtnUbahActionPerformed(java.awt.event.ActionEvent evt) {                                        
        try {
            String idUser = getSelectedIdUser();
            if (TextIdKaryawan.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Pilih data yang ingin diubah");
            } else if (idUser == null) {
                JOptionPane.showMessageDialog(null, "Pilih ID User terlebih dahulu");
            } else {
                crudObj.ubahKaryawan(
                    TextIdKaryawan.getText(),
                    idUser, 
                    TextNamaKaryawan.getText(), 
                    TextEmail.getText(), 
                    TextAlamat.getText(), 
                    TextNoTelpon.getText()
                );
                loadDataTabel();
                clearForm();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }                                       

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {                                         
        try {
            if (TextIdKaryawan.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus");
            } else {
                int Pilihan = JOptionPane.showConfirmDialog(null, "Yakin hapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                if(Pilihan == JOptionPane.YES_OPTION) {
                    crudObj.hapusKaryawan(TextIdKaryawan.getText());
                    loadDataTabel();
                    clearForm();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }                                        

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {                                         
        clearForm();
    }                                        

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        int baris = jTable1.getSelectedRow();
        
        String id_karyawan = jTable1.getValueAt(baris, 0).toString();
        String id_user = jTable1.getValueAt(baris, 1).toString();
        String nama = jTable1.getValueAt(baris, 2).toString();
        String email = jTable1.getValueAt(baris, 3) != null ? jTable1.getValueAt(baris, 3).toString() : "";
        String alamat = jTable1.getValueAt(baris, 4) != null ? jTable1.getValueAt(baris, 4).toString() : "";
        String no_telpon = jTable1.getValueAt(baris, 5) != null ? jTable1.getValueAt(baris, 5).toString() : "";
        
        TextIdKaryawan.setText(id_karyawan);
        TextNamaKaryawan.setText(nama);
        TextEmail.setText(email);
        TextAlamat.setText(alamat);
        TextNoTelpon.setText(no_telpon);
        
        for (int i = 0; i < ComboBoxIdUser.getItemCount(); i++) {
            if (ComboBoxIdUser.getItemAt(i).startsWith(id_user + " - ")) {
                ComboBoxIdUser.setSelectedIndex(i);
                break;
            }
        }
    }                                    

    private void TextPencarianKeyReleased(java.awt.event.KeyEvent evt) {                                          
        String c=TextPencarian.getText();
        String cari="select * from karyawan where id_karyawan like '%"+c+"%' "+
                    "or id_user like '%"+c+"%' or nama_karyawan like '%"+c+"%' or email like '%"+c+"%' or alamat_karyawan like '%"+c+"%' or no_telpon like '%"+c+"%'";
        crudObj.loadData(jTable1, cari);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnSimpan;
    private javax.swing.JButton BtnUbah;
    private javax.swing.JComboBox<String> ComboBoxIdUser;
    private javax.swing.JTextField TextAlamat;
    private javax.swing.JTextField TextEmail;
    private javax.swing.JTextField TextIdKaryawan;
    private javax.swing.JTextField TextNamaKaryawan;
    private javax.swing.JTextField TextNoTelpon;
    private javax.swing.JTextField TextPencarian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}