/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import pbo_2310010231.CRUD;

/**
 *
 * @author wijaya
 */
public class FrameInventory extends javax.swing.JFrame {

    CRUD crudObj;
    /**
     * Creates new form FrameInventory
     */
    public FrameInventory() {
        initComponents();
        this.setLocationRelativeTo(null);
        crudObj = new CRUD();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Inventory");
        
        loadDataTabel();
        loadIdKaryawanComboBox();
    }
    
    public void loadDataTabel() {
        crudObj.loadData(jTable1, "SELECT * FROM inventory");
    }
    
    public void clearForm() {
        TextIdInventory.setText("");
        ComboBoxIdKaryawan.setSelectedIndex(0);
        TextNamaBarang.setText("");
        TextKategoriBarang.setText("");
        TextJumlah.setText("");
    }
    
    public void loadIdKaryawanComboBox() {
        try {
            ComboBoxIdKaryawan.removeAllItems();
            
            ResultSet rs = crudObj.koneksiDB.createStatement().executeQuery("SELECT id_karyawan, nama_karyawan FROM karyawan");
            
            ComboBoxIdKaryawan.addItem("Pilih ID Karyawan");
            
            while (rs.next()) {
                ComboBoxIdKaryawan.addItem(rs.getString("id_karyawan") + " - " + rs.getString("nama_karyawan"));
            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat ID Karyawan: " + e.getMessage());
        }
    }
    
    public String getSelectedIdKaryawan() {
        if (ComboBoxIdKaryawan.getSelectedIndex() == 0) {
            return null;
        }
        String selectedItem = ComboBoxIdKaryawan.getSelectedItem().toString();
        String idKaryawan = selectedItem.split(" ")[0];
        return idKaryawan;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TextIdInventory = new javax.swing.JTextField();
        ComboBoxIdKaryawan = new javax.swing.JComboBox<>();
        TextJumlah = new javax.swing.JTextField();
        TextNamaBarang = new javax.swing.JTextField();
        TextKategoriBarang = new javax.swing.JTextField();
        TextPencarian = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnSimpan = new javax.swing.JButton();
        BtnUbah = new javax.swing.JButton();
        BtnHapus = new javax.swing.JButton();
        BtnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Form Inventory");

        jLabel2.setText("Id Inventory");

        jLabel3.setText("Id Karyawan");

        jLabel4.setText("Jumlah");

        jLabel5.setText("Nama Barang");

        jLabel6.setText("Kategori Barang");

        jLabel7.setText("Pencarian");

        TextIdInventory.setEditable(false);

        ComboBoxIdKaryawan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        TextPencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextPencarianKeyReleased(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        BtnSimpan.setText("Simpan");
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });

        BtnUbah.setText("Ubah");
        BtnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUbahActionPerformed(evt);
            }
        });

        BtnHapus.setText("Hapus");
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });

        BtnClear.setText("Clear");
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(BtnSimpan, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TextIdInventory)
                                            .addComponent(ComboBoxIdKaryawan, 0, 100, Short.MAX_VALUE))
                                        .addGap(71, 71, 71)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(30, 30, 30)
                                                .addComponent(TextNamaBarang))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(TextKategoriBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(104, 104, 104)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(BtnUbah)
                                        .addGap(18, 18, 18)
                                        .addComponent(BtnHapus)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BtnClear)))
                                .addGap(18, 18, 18)
                                .addComponent(TextPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TextJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(TextPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(TextIdInventory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(ComboBoxIdKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextKategoriBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(TextJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnUbah)
                    .addComponent(BtnSimpan)
                    .addComponent(BtnHapus)
                    .addComponent(BtnClear))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {                                          
        try {
            String idKaryawan = getSelectedIdKaryawan();
            if (idKaryawan == null) {
                JOptionPane.showMessageDialog(null, "Pilih ID Karyawan terlebih dahulu");
            } else if (TextNamaBarang.getText().isEmpty() || TextJumlah.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Nama Barang dan Jumlah tidak boleh kosong");
            } else {
                crudObj.simpanInventory(
                    idKaryawan,
                    TextNamaBarang.getText(),
                    TextKategoriBarang.getText(),
                    TextJumlah.getText()
                );
                loadDataTabel();
                clearForm();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }                                         

    private void BtnUbahActionPerformed(java.awt.event.ActionEvent evt) {                                        
        try {
            String idKaryawan = getSelectedIdKaryawan();
            if (TextIdInventory.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Pilih data yang ingin diubah");
            } else if (idKaryawan == null) {
                JOptionPane.showMessageDialog(null, "Pilih ID Karyawan terlebih dahulu");
            } else {
                crudObj.ubahInventory(
                    TextIdInventory.getText(),
                    idKaryawan,
                    TextNamaBarang.getText(),
                    TextKategoriBarang.getText(),
                    TextJumlah.getText()
                );
                loadDataTabel();
                clearForm();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }                                       

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {                                         
        try {
            if (TextIdInventory.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus");
            } else {
                int Pilihan = JOptionPane.showConfirmDialog(null, "Yakin hapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                if(Pilihan == JOptionPane.YES_OPTION) {
                    crudObj.hapusInventory(TextIdInventory.getText());
                    loadDataTabel();
                    clearForm();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }                                        

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {                                         
        clearForm();
    }                                        

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        int baris = jTable1.getSelectedRow();
        
        String id_inventory = jTable1.getValueAt(baris, 0).toString();
        String id_karyawan = jTable1.getValueAt(baris, 1).toString();
        String nama_barang = jTable1.getValueAt(baris, 2).toString();
        String kategori = jTable1.getValueAt(baris, 3) != null ? jTable1.getValueAt(baris, 3).toString() : "";
        String jumlah = jTable1.getValueAt(baris, 4).toString();
        
        TextIdInventory.setText(id_inventory);
        TextNamaBarang.setText(nama_barang);
        TextKategoriBarang.setText(kategori);
        TextJumlah.setText(jumlah);
        
        for (int i = 0; i < ComboBoxIdKaryawan.getItemCount(); i++) {
            if (ComboBoxIdKaryawan.getItemAt(i).startsWith(id_karyawan + " - ")) {
                ComboBoxIdKaryawan.setSelectedIndex(i);
                break;
            }
        }
    }                                    

    private void TextPencarianKeyReleased(java.awt.event.KeyEvent evt) {                                          
        String c=TextPencarian.getText();
        String cari="select * from inventory where id_inventory like '%"+c+"%' "+
                    "or id_karyawan like '%"+c+"%' or nama_barang like '%"+c+"%' or kategori_barang like '%"+c+"%' or jumlah like '%"+c+"%'";
        crudObj.loadData(jTable1, cari);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameInventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnSimpan;
    private javax.swing.JButton BtnUbah;
    private javax.swing.JComboBox<String> ComboBoxIdKaryawan;
    private javax.swing.JTextField TextIdInventory;
    private javax.swing.JTextField TextJumlah;
    private javax.swing.JTextField TextKategoriBarang;
    private javax.swing.JTextField TextNamaBarang;
    private javax.swing.JTextField TextPencarian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}